version: '3.8'

services:
  app:
    build:
      context: '.'
    command: 'server'
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes_from:
    - appdata
    depends_on:
      - "mysql"

  appdata:
    image: tianon/true
    volumes:
      - ".:/workspace"
      - ./bundle_cache:/bundle:rw,delegated

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes_from:
      - dbdata
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql
